[package]
name = "tma-16-rs"
version = "0.1.0"
authors = ["Dante Falzone <dante.j.falzone@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# let's try and keep this section short, if not empty
